# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      #- id: check-symlinks
      - id: debug-statements
      #- id: requirements-txt-fixer
      - id: fix-encoding-pragma
        #args: ['--remove']
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '(.*examples/.*)'
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-toml
      #- id: check-json
      - id: check-yaml
        #exclude: '(conda/meta.yaml|.pep8speaks.yml)'

  #- repo: "https://github.com/asottile/blacken-docs"
    #rev: "v1.11.0"
    #hooks:
      #- id: "blacken-docs"
        #name: "Format docs (blacken-docs)"
        #args: ["-l", "64"]
        #additional_dependencies:
          #- "black==21.9b0"

  #- repo: https://github.com/PyCQA/doc8
    #rev: 0.9.1
    #hooks:
      #- id: doc8
        #args:
          #- '--max-line-length=90'
          #- '--ignore=D001'

  #- repo: https://github.com/pre-commit/pygrep-hooks
    #rev: v1.9.0
    #hooks:
      #- id: rst-backticks
        ## exclude: ChangeLog\.rst$
      #- id: rst-directive-colons
      #- id: rst-inline-touching-normal

  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        files: ^usb_protocol.*\.py$
        args:
          - --in-place
          - --remove-duplicate-keys
          - --remove-unused-variables

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        files: ^usb_protocol.*\.py$
        additional_dependencies: ["flake8-bugbear"]

#  - repo: https://github.com/hadialqattan/pycln
#    rev: v0.0.1-beta.3
#    hooks:
#      - id: pycln
#        args: [--config=pyproject.toml]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--settings-path=pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
    - id: mypy
      additional_dependencies:
        - construct>=2.10.67
        - construct-typing>=0.5.2
      args:
        - --follow-imports=normal
        - --install-types
        - --non-interactive
      files: ^usb_protocol.*\.py$

#  - repo: https://github.com/psf/black
#    rev: 20.8b1
#    hooks:
#      - id: black
#        args: [--config=pyproject.toml]

  #- repo: https://github.com/PyCQA/bandit
    #rev: 1.7.0
    #hooks:
      #- id: bandit
        ##args: ["-ll", "-b", "bandit_baseline.json"]

  #- repo: https://github.com/PyCQA/pylint
    #rev: v2.11.1
    #hooks:
    #- id: pylint
      #additional_dependencies:
        #- construct==2.10.67
        #- construct-typing==0.5.2
      #exclude: '(.*examples/.*)'
      #args:
        #[
          #"-rn",
          #"-sn",
          #"--fail-under=8.10",
        #]
